# Generated by Django 6.0.5 on 2026-05-27 19:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_alter_doctoravailability_doctor'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['weekday', 'start_time']},
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'weekday', 'start_time', 'end_time'), name='unique_doctor_schedule'),
        ),
    ]
