# Generated by Django 6.0.5 on 2026-06-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0003_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
