# Generated by Django 6.0.5 on 2026-06-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointments_doctor_alter_appointments_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
