# Generated by Django 6.0.5 on 2026-05-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
